### ISSUE TITLE
Deployment to GitHub Pages

### ISSUE THREAD

**Issue by olange** [uzufly/showcase-cesium-ifc#1]
## Actions

- [x] Have Parcel generate relative links instead of absolute ones `DONE` 17.03.2023 OL use `--public-url ./` when building;
see parcel-bundler/website#30
- [x] Craft a workflow to build & deploy to GitHub Pages `DONE` 17.03.2023 OL used the [static workflow](#issuecomment-1474056924) herebelow, with additional install & build steps

## Reference articles

* [GitHub Actions › Static HTML](https://github.com/uzufly/showcase-cesium-ifc/actions/new?category=pages)
* [GitHub Marketplace › Deploy to GitHub Pages (GitHub Action)](https://github.com/marketplace/actions/deploy-to-github-pages)

**Comment by olange** [comment]
```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```
